"""Add payments table

Revision ID: 4810e499a4f1
Revises: c1523f4b8ca8
Create Date: 2021-09-24 00:03:51.327406

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4810e499a4f1"
down_revision = "c1523f4b8ca8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payments",
        sa.Column("uuid", sa.String(length=32), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=5), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("charge_id", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("payments")
    # ### end Alembic commands ###
