"""Create auction descriptor

Revision ID: 4de7a165a4d2
Revises: aa67d02455c9
Create Date: 2021-09-18 21:10:37.746825

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4de7a165a4d2"
down_revision = "aa67d02455c9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auctions_descriptors",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "auctions", sa.Column("ends_at", sa.DateTime(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("auctions", "ends_at")
    op.drop_table("auctions_descriptors")
    # ### end Alembic commands ###
