"""Add tables for event sourcing snapshots

Revision ID: 83b8b82bd255
Revises: f76a3a08cc3b
Create Date: 2021-10-02 14:01:45.035375

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
from itca.db import GUID, JSONB

revision = "83b8b82bd255"
down_revision = "f76a3a08cc3b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "snapshots",
        sa.Column("uuid", GUID(), nullable=False),
        sa.Column("aggregate_uuid", GUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("data", JSONB(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        "ix_snapshots_aggregate_version",
        "snapshots",
        ["aggregate_uuid", "version"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_snapshots_aggregate_version", table_name="snapshots")
    op.drop_table("snapshots")
    # ### end Alembic commands ###
