"""Add current price to auction model

Revision ID: 873d26933b37
Revises: 4de7a165a4d2
Create Date: 2021-09-18 21:19:52.103056

"""
import sqlalchemy as sa
from alembic import op

from itca.db.jsonb import JSONB

# revision identifiers, used by Alembic.
revision = "873d26933b37"
down_revision = "4de7a165a4d2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "auctions",
        sa.Column("current_price", JSONB(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("auctions", "current_price")
    # ### end Alembic commands ###
