"""Create auction and bid models

Revision ID: aa67d02455c9
Revises:
Create Date: 2021-09-17 23:21:44.125886

"""
import sqlalchemy as sa
from alembic import op

from itca.db.jsonb import JSONB

# revision identifiers, used by Alembic.
revision = "aa67d02455c9"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auctions",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("starting_price", JSONB(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bids",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("amount", JSONB(), nullable=False),
        sa.Column("bidder_id", sa.BigInteger(), nullable=False),
        sa.Column("auction_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["auction_id"],
            ["auctions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bids")
    op.drop_table("auctions")
    # ### end Alembic commands ###
