"""Create model for outbox

Revision ID: c1523f4b8ca8
Revises: 7ee5422d729d
Create Date: 2021-09-23 22:07:47.445258

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
from itca.db import JSONB

revision = "c1523f4b8ca8"
down_revision = "7ee5422d729d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbox_messages",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("listener", sa.String(), nullable=False),
        sa.Column("event", sa.String(), nullable=False),
        sa.Column("event_payload", JSONB(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("outbox_messages")
    # ### end Alembic commands ###
