"""Add tables for event sourcing models

Revision ID: f76a3a08cc3b
Revises: 2743a62623ef
Create Date: 2021-09-30 21:44:12.582449

"""
import sqlalchemy as sa
from alembic import op

from itca.db import GUID, JSONB

# revision identifiers, used by Alembic.
revision = "f76a3a08cc3b"
down_revision = "2743a62623ef"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "aggregates",
        sa.Column("uuid", GUID(), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "events",
        sa.Column("uuid", GUID(), nullable=False),
        sa.Column("aggregate_uuid", GUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("data", JSONB(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        "ix_events_aggregate_version",
        "events",
        ["aggregate_uuid", "version"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_events_aggregate_version", table_name="events")
    op.drop_table("events")
    op.drop_table("aggregates")
    # ### end Alembic commands ###
