"""Add table for paying for won item process manager state

Revision ID: f7e66b8528bb
Revises: 4810e499a4f1
Create Date: 2021-09-25 13:27:46.374732

"""
import sqlalchemy as sa
from alembic import op

from itca.db import GUID

# revision identifiers, used by Alembic.
revision = "f7e66b8528bb"
down_revision = "4810e499a4f1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "paying_for_won_auction_pm",
        sa.Column(
            "auction_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("winner_id", sa.BigInteger(), nullable=False),
        sa.Column("winning_bid_currency", sa.String(length=3), nullable=False),
        sa.Column("winning_bid_amount", sa.Numeric(), nullable=False),
        sa.Column("payment_uuid", GUID(), nullable=False),
        sa.Column(
            "payment_finished_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "shipment_started_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "shipment_sent_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.PrimaryKeyConstraint("auction_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("paying_for_won_auction_pm")
    # ### end Alembic commands ###
