@startuml
!include https://raw.githubusercontent.com/bschwarz/puml-themes/master/themes/materia/puml-theme-materia.puml
skinparam defaultFontSize 24

actor Licytujący as bidder
participant Frontend as frontend
participant Backend as backend
participant PaymentProvider as provider

bidder -> frontend: tak, chcę to kupić za 100 PLN!
frontend -> backend
backend -> provider: obciąż token #123456 na 100 PLN

@enduml