name: Implementing The Clean Architecture checks

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip poetry
        cd auctioning_platform
        poetry install
    - name: Run lintes
      run: |
        poetry run make check
    - name: Test with pytest
      run: |
        poetry run pytest
